### ISSUE TITLE
WooCommerce Stellar Plugin doesn't work.

### ISSUE THREAD

**Issue by nika90426** [Prospress/woocommerce-stellar#61]
Hi, Thank you for your share.
I've installed this plugin in wordpress 4.2.3 and the following warning has been appeared.

"Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'WC_Stellar' not found in C:\xampp\htdocs\wordpress\wp-includes\plugin.php on line 496"

Why this happens and what's the solution?
Thanx.

**Comment by thenbrent** [comment]
> Why this happens and what's the solution?

That's very unusual, sorry for the trouble. It sounds like the uploaded plugin may be missing a file. Could you please send temporary admin credentials to your site to support@prospress.com? That way, we can take a look and try to delete/re-upload the plugin's zip file if there are files missing.

**Comment by nika90426** [comment]
Thank you for your cooperation.
I've just tested on my local environment.
First I've installed 'xampp' and extracted the 'wordpress 4.2.3' to 'htdocs', and then installed the 'woocommerce-stellar' plugin, then it happened. 
I'll attach the snapshot.
I really need your help.
Thanx.
![issuer](https://cloud.githubusercontent.com/assets/13570086/9000390/80a5c2d0-36fb-11e5-8785-510b72f3f610.jpg)

**Comment by jconroy** [comment]
Hi @nika90426 

It looks like you don't have WooCommerce installed. 

Try installing that either:
* through the WP Dashboard OR
* by manually downloading from http://www.woothemes.com/woocommerce/ ( or https://wordpress.org/plugins/woocommerce/ ) and then upload and install it on your site.

**Comment by nika90426** [comment]
It works now.
Thank you for your kindness.

**Comment by jconroy** [comment]
No problems

**Comment by nika90426** [comment]
Hi @jconroy !
Is there any manual to start woocommerce-stellar?

**Comment by jconroy** [comment]
Check out https://wordpress.org/plugins/woocommerce-stellar/installation/ for the plugin specific stuff and Stellar doco for how to use Stellar itself.

For WooCommerce which handles most of the work you should check out their site http://www.woothemes.com/woocommerce/store-owners/ and documentation http://docs.woothemes.com/documentation/plugins/woocommerce/.

Google can probably help you out as well :smile:

**Comment by nika90426** [comment]
Thanks,very much.:smile:
